[package]
name = "backlog"
version = "0.2.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
error-chain = "0.10"
url = "1.5"
